networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1

services:

  haproxy:
    image: haproxytech/haproxy-ubuntu-quic:3.2
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
      - "5555:5555"
      - "9999:9999"
    # volumes:
    #   - "./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
    networks:
      custom_net:
        ipv4_address: 172.16.0.10
  web1:
    image: jmalloc/echo-server
    networks:
      custom_net:
        ipv4_address: 172.16.0.11

  web2:
    image: jmalloc/echo-server
    networks:
      custom_net:
        ipv4_address: 172.16.0.12

